name: PyTests

on:
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      POETRY_VIRTUALENVS_CREATE: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Run tests
        run: |
          uv run pytest ./tests/unit
